version: '3'

services:
  db:
    env_file: superset/.env
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_home:/var/lib/postgresql/data
  superset:
      build:
        context: ./superset
        dockerfile: Dockerfile
      container_name: superset-simple
      environment:
        - ADMIN_USERNAME=admin
        - ADMIN_EMAIL=admin@superset.com
        - ADMIN_PASSWORD=admin
      ports:
        - '8088:8088'
volumes:
  db_home:
    external: false